# Config file for jet classification

#------------------------------------------------------------------
# Note: We will read processing parameters from the loaded file, 
# rather than from this config file.
# See subjets_unshuffled.h5 and subjet_graphs.h5 for the set
# of parameters that are read from the loaded file.
#------------------------------------------------------------------

#------------------------------------------------------------------
# These following parameters are used only in ML analysis
#------------------------------------------------------------------

# Size of labeled data to load (i.e. number of jets)
n_train: 4000
n_val:   0
n_test:  1000

# Which subjet collections to use
subjet_basis: 'inclusive'
r: [0.05]

# Classification labels
label_0: 'gluon'
label_1: 'quark'

# Select model: particle_gnn, subjet_gnn
models: [particle_gnn, subjet_gnn]

particle_gnn:
    graph_types: ['fully_connected']
    epochs: 5
    batch_size: 128

subjet_gnn:
    graph_types: ['laman_naive', 'laman_1N', 'laman_1N2N']
    epochs: 10
    batch_size: 128
