# Config file for jet classification

#------------------------------------------------------------------
# Note: We will read processing parameters from the loaded file, 
# rather than from this config file.
# See subjets_unshuffled.h5 and subjet_graphs.h5 for the set
# of parameters that are read from the loaded file.
#------------------------------------------------------------------

#------------------------------------------------------------------
# These following parameters are used only in ML analysis
#------------------------------------------------------------------

# Size of labeled data to load (i.e. number of jets)
n_train: 4000
n_val:   500
n_test:  500

# Which subjet collections to use
subjet_basis: 'inclusive'
r: [0.05]

# Classification labels
label_0: 'gluon'
label_1: 'quark'

# Select model: particle_gcn, particle_gat, subjet_gcn, subjet_gat
models: ['particle_gcn', 'particle_gat']

particle_gcn:
    graph_types: ['fully_connected']
    edge_features: False
    hidden_dim: 64
    batch_size: 128
    epochs: 5
    learning_rate: 0.001

particle_gat:
    graph_types: ['fully_connected']
    edge_features: False
    hidden_dim: 8
    n_heads: 8
    batch_size: 128
    epochs: 5
    learning_rate: 0.001

subjet_gcn:
    graph_types: ['laman_naive', 'laman_1N', 'laman_1N2N']
    edge_features: False
    hidden_dim: 64
    batch_size: 128
    epochs: 5
    learning_rate: 0.001

subjet_gat:
    graph_types: ['laman_naive', 'laman_1N', 'laman_1N2N']
    edge_features: True
    hidden_dim: 8
    n_heads: 8
    batch_size: 128
    epochs: 5    
    learning_rate: 0.001
